# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2025
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
name: Lint Code Base
# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
permissions: read-all
jobs:
  get-sloc:
    name: Count Lines of Code
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
        with:
          persist-credentials: false
      - name: Setup Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # 6.4.0
        with:
          go-version: ">=1.20.0"
      - name: Install dependencies
        run: go install github.com/boyter/scc/v3@latest
      - name: Run scc tool
        run: scc --format wide
  check-broken-links:
    name: Check documentation external links
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
        with:
          persist-credentials: false
      - name: Check broken links
        uses: gaurav-nelson/github-action-markdown-link-check@4a1af151f4d7cf4d8f8ac5780597672a3671b88b # 1.0.17
  check-super-linter:
    name: Check syntax (super-linter)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
        with:
          persist-credentials: false
      - name: Run super-linter validation
        uses: super-linter/super-linter@9e863354e3ff62e0727d37183162c4a88873df41 # 8.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_CHECKOV: false
          VALIDATE_NATURAL_LANGUAGE: false
          LINTER_RULES_PATH: /
          EDITORCONFIG_FILE_NAME: .editorconfig-checker.json
          DEFAULT_BRANCH: ${{ github.event.repository.default_branch || 'main'}}
